name: Envoi Mail Automatique SOAN

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  check-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5

      - name: Configuration Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Exécution du script
        run: node .github/scripts/send_mail.js
