name: Envoi Mail Automatique SOAN

on:
  schedule:
    # Vérification toutes les 30 minutes
    - cron: '0,30 * * * *'
  workflow_dispatch: # Permet le déclenchement manuel pour les tests

jobs:
  check-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configuration Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installation des dépendances
        run: npm install firebase-admin nodemailer

      - name: Exécution du script d'envoi
        run: node .github/scripts/send_mail.js
